### ISSUE TITLE
Endre feature image

### ISSUE THREAD

**Issue by soderlind** [DekodeInteraktiv/hogan-simple-posts#4]
Endre denne https://github.com/DekodeInteraktiv/hogan-simple-posts/blob/430e1a23ee8a5e5d936844da002b6039e61ae38b/assets/template.php#L28

Til, enten legge til `<figure></figure>`wrapper og after_image hook slik som i https://github.com/DekodeInteraktiv/hogan-content-grid/pull/17

eller noe slik:
```php
<div class="featured-image">
        <?php echo apply_filter('hogan/module/simple_posts/featured_image', get_the_post_thumbnail( null, apply_filters( 'hogan/module/simple_posts/image_size', 'post-thumbnail', $this ) ) ), get_post_thumbnail_id( null ) ); ?>
</div>
```
Så vi kan bruke:

```php
add_filter( 'hogan/module/simple_posts/featured_image, function ( $featured_image, $featured_image_id) {
        /* vår kode her*/

        return $featured_image;
}, 10, 2 );
```

**Comment by pederan** [comment]
@soderlind Lagt inn i v 1.1.3
